stages:
  - unit-testing
  - deploy

image: markadams/chromium-xvfb-js:latest-onbuild

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/

before_script:
  - npm ci --cache .npm --prefer-offline

test:
  stage: unit-testing
  tags:
    - docker
  script: 
    - npm run test -- --no-watch --no-progress
  artifacts:
    reports:
      junit: test-results.xml
    expire_in: 1 week
