stages:
  - unit-test
  - deploy

variables:
  GIT_DEPTH: "3"

image: timbru31/node-chrome:22-slim

cache:
  key: 
    files: 
      - package-lock.json
  paths:
    - .npm

before_script:
  - npm ci --cache .npm --prefer-offline

unit-test:
  stage: unit-test
  tags:
    - docker
  script: 
    - npx ng test --no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage
  artifacts:
    paths:
      - coverage/
    expire_in: 4 days

