stages:
  - unit-test
  - deploy

variables:
  GIT_DEPTH: "3"
  GIT_STRATEGY: fetch
  
  GIT_TRACE: "1"
  GIT_CURL_VERBOSE: "1"
  CI_DEBUG_TRACE: "true"

image: timbru31/node-chrome:22-slim

cache:
  key: 
    files: 
      - package-lock.json
  paths:
    - .npm

before_script:
  - npm ci --cache .npm --prefer-offline

unit-test:
  stage: unit-test
  tags:
    - docker
  script:
    - echo forTestTest
    - whoami
    - npx ng test --no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage
  artifacts:
    paths:
      - coverage/
    expire_in: 4 days

