stages:
  - unit-test
  - deploy

variables:
  GIT_DEPTH: "3"
  GIT_STRATEGY: clone

image: timbru31/node-chrome:22-slim

cache:
  key: 
    files: 
      - package-lock.json
  paths:
    - .npm

unit-test:
  stage: unit-test
  tags:
    - docker
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npx ng test --no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage
  artifacts:
    paths:
      - coverage/
    expire_in: 4 days

push:
  stage: deploy
  tags:
    - docker
  cache: {}
  image: docker:cli
  script:
    - echo $CI_REGISTRY
    - echo $GITLAB_USER_LOGIN
    - docker login -u $GITLAB_USER_LOGIN -p $TOKEN_DOCKER_REGISTRY $CI_REGISTRY
    - docker build -t registry.gitlab.com/igorfilin/personal-cabinet:$CI_COMMIT_SHA .
    - docker push registry.gitlab.com/igorfilin/personal-cabinet:$CI_COMMIT_SHA
  needs:
    - unit-test
  when: manual

