stages:
  - unit-test
  - deploy

variables:
  GIT_DEPTH: "3"
  GIT_STRATEGY: clone

image: timbru31/node-chrome:22-slim

cache:
  key: 
    files: 
      - package-lock.json
  paths:
    - .npm

unit-test:
  stage: unit-test
  tags:
    - docker
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npx ng test --no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage
  artifacts:
    paths:
      - coverage/
    expire_in: 4 days

build-push:
  stage: deploy
  image: quay.io/buildah/stable
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
    IMAGE_TAG: ${CI_COMMIT_TAG#v}
    FQ_IMAGE_NAME: "registry.gitlab.com/igorfilin/personal-cabinet:$IMAGE_TAG"
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - buildah build -t $FQ_IMAGE_NAME
    - buildah push $FQ_IMAGE_NAME
  needs:
    - unit-test
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
      when: manual
  